version: '3.8'
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: etzgit_api:dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/etzgit
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/api:/usr/src/app

  web:
    build:
      context: ./apps/web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etzgit
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
