name: AI Branch Validation

on:
  push:
    branches:
      - 'ai-upgrade-*'

jobs:
  validate:
    name: Validate AI-generated branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit || pnpm -w test:unit

      - name: Run e2e tests
        run: pnpm test:e2e || pnpm -w test:e2e
