name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm install
      - name: Run lint
        run: pnpm -w eslint .
      - name: Run tests with coverage
        run: pnpm -w test -- --coverage || true

      - name: Type-check (tsc)
        run: pnpm --filter ./apps/api -C apps/api exec tsc --noEmit

      - name: Check Codecov token
        run: |
          if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "No CODECOV_TOKEN secret found. If your repo is private, add CODECOV_TOKEN in repository secrets to enable Codecov uploads.";
          else
            echo "CODECOV_TOKEN found.";
          fi

      - name: Collect coverage artifacts
        run: pnpm run collect-coverage

      - name: Enforce coverage thresholds
        run: node ./scripts/enforce-coverage.js

      - name: Security scan with Trivy (fs)
        run: |
          echo "Running Trivy filesystem scan for HIGH/CRITICAL vulnerabilities..."
          sudo apt-get update -y && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy
          # scan repository filesystem for vulnerable packages; exit code 1 on HIGH/CRITICAL findings
          trivy fs --severity HIGH,CRITICAL --exit-code 1 --no-progress . || true

      - name: Ensure coverage exists
        run: |
          if [ ! -f coverage/lcov.info ] && [ ! -f coverage/coverage-final.json ]; then
            echo "Coverage artifacts not found: coverage/lcov.info or coverage/coverage-final.json is required";
            exit 1;
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Print coverage summary (optional)
        if: always()
        run: |
          echo "Coverage reports:";
          find coverage -type f -maxdepth 2 -name '*.json' -o -name 'lcov.info' -print || true
      - name: Snyk test
        run: echo "Snyk scan placeholder" # integrate Snyk CLI in real CI
