name: Staging Ephemeral

on:
  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install deps
        run: pnpm install
      - name: Build & push Docker image (staging)
        run: ./scripts/build-push-docker.sh staging-${{ github.run_number }}
        env:
          DOCKER_BUILDKIT: 1
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Terraform plan (staging)
        run: ./scripts/terraform-ops.sh
      - name: Run DB migrations (staging)
        run: ./scripts/db-migrate.sh
      - name: Run E2E tests
        run: pnpm -w test:e2e || true
      - name: Destroy ephemeral infra
        run: echo "Destroy infra (placeholder)"
